<a href="https://colab.research.google.com/github/SangamSilwal/Numpy-and-panda/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
np.array([1,2,3,0],dtype = bool)

array([ True,  True,  True, False])

In [6]:
np.array([1,2,3],dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [11]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
# using ones and zeros in numpy
# ones and zeros are use to initialize neural network in deep learning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# using random in numpy
np.random.random((3,4))

array([[0.38055075, 0.51387106, 0.97149321, 0.74847108],
       [0.79371699, 0.98920648, 0.49860587, 0.06516624],
       [0.46671335, 0.60596249, 0.20241697, 0.57354963]])

In [18]:
# using np.linespace
# syntax = np.linspace("lowerrange",upperrange,totalnumbers)
np.linspace(-10,10,10)
# linspace generate linearly sperated point in a given range


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
# np.identity
# we can create a identity matrix using np.identity
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
# using different ways to create an array
a1 = np.arange(10,dtype=np.int32) #This will create a array i.e vector
a2 = np.arange(12,dtype=float).reshape(3,4)  #this is a matrix
a3 = np.arange(8).reshape(2,2,2) #we call this tensor

In [26]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [29]:
# ndim
a1.ndim
a2.ndim
a3.ndim

3

In [32]:
# shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [34]:
# size
a1.size
a2.size

12

In [43]:
# itemsize
print(a1.itemsize)
print(a1.dtype)

4
int32


# Changing datatype


In [44]:
print(a3.dtype)

int64


In [46]:
a3.astype(np.int32)
# astype is used to change the data type of the given data

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation

In [56]:
# scalar operation
# arithmetic operation
# done
a1 = np.arange(12).reshape(3,4)
a2 = np.random.random(12).reshape(3,4)


In [58]:
a1**a2

array([[0.        , 1.        , 1.7801691 , 1.15562082],
       [2.04038396, 2.05499329, 1.26279937, 5.57095594],
       [5.12983065, 7.12371072, 4.21995094, 2.08814684]])

In [59]:
a1==a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [61]:
print(a2.sum())

6.824850734951877


In [5]:
array1 = np.arange(1,13).reshape(3,4)
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# performing max/min/sum/product
# we have to understand that ---> 0->col and 1->row
np.max(array1,axis=1)
np.min(array1,axis=0)
np.sum(array1,axis=0)

array([15, 18, 21, 24])