<a href="https://colab.research.google.com/github/SangamSilwal/Numpy-and-panda/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Indexing and slicing in numpy

In [ ]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[2,0,0]
a3[2,2,0]

24

Slicing in numpy

In [ ]:
print(a1[:4:2])
print(a1)

[0 2]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a2)
a2[0,:] #this will print row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [ ]:
a2[:,2] #this will print colum

array([ 2,  6, 10])

In [ ]:
a2[1,1:2]

#SO here the slicing syntax generally refer a2[required row,required colum]
print(a2[1:,2:])
print(a2[::2,1::2])

[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]


In [ ]:
print(a2)
a2[1:,1::2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 5,  7],
       [ 9, 11]])

In [ ]:
a1[2:5:2]
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 3d array
print(a3)
a3[1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

# Iterating in Numpy array

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a3
for i in np.nditer(a3):  #using this syntax we can print all the iten of the array
  print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
#reshape

In [ ]:
#transpose
print(a2)
np.transpose(a2)
a2.T#this is simple transpose function

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel
a3.ravel()    #ravel function will convert any Dimension array to one D array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking in numpy array

In [ ]:
# The two function used for stacking are:
# hstack
# vstack
# Note: We should provide a tuple inside the stack

a4 = np.arange(12).reshape(3,4)
print(a4)
a5 = np.arange(12,24).reshape(3,4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [ ]:
# horizontal splitting
# It operates on column
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
#vertical splitting
# it operates on row
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]